--------------------------------------------------------
--  파일이 생성됨 - 월요일-2월-19-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_PRODUCT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBL_PRODUCT" 
   (	"ITEM_NO" VARCHAR2(100 BYTE), 
	"ITEM_NAME" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER, 
	"S_RATE" NUMBER, 
	"P_RATE" NUMBER, 
	"CONTENTS" VARCHAR2(100 BYTE), 
	"SELLYN" CHAR(1 BYTE), 
	"TRANS_INFO" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TBL_PRODUCT
SET DEFINE OFF;
Insert into SYSTEM.TBL_PRODUCT (ITEM_NO,ITEM_NAME,PRICE,S_RATE,P_RATE,CONTENTS,SELLYN,TRANS_INFO) values ('CLO1001','남성 기본 티셔츠',19900,0,0,'면 100%, 부드러운 착용감의 남성용 기본 티셔츠','N','무료 배송');
Insert into SYSTEM.TBL_PRODUCT (ITEM_NO,ITEM_NAME,PRICE,S_RATE,P_RATE,CONTENTS,SELLYN,TRANS_INFO) values ('CLO1002','여성 봄 가디건',29900,0,0,'가볍고 포근한 여성용 봄 가디건','Y','무료 배송');
Insert into SYSTEM.TBL_PRODUCT (ITEM_NO,ITEM_NAME,PRICE,S_RATE,P_RATE,CONTENTS,SELLYN,TRANS_INFO) values ('CLO1003','언발란스 스커트',24900,0,0,'트렌디한 디자인의 언발란스 스커트','N','무료 배송');
Insert into SYSTEM.TBL_PRODUCT (ITEM_NO,ITEM_NAME,PRICE,S_RATE,P_RATE,CONTENTS,SELLYN,TRANS_INFO) values ('CLO1004','캐주얼 청바지',39900,0,0,'편안한 착용감의 스타일리시 캐주얼 청바지','N','착불 배송');
Insert into SYSTEM.TBL_PRODUCT (ITEM_NO,ITEM_NAME,PRICE,S_RATE,P_RATE,CONTENTS,SELLYN,TRANS_INFO) values ('CLO1005','코튼 롱 드레스',45900,0,0,'여름에 어울리는 시원한 코튼 소재의 롱 드레스','Y','무료 배송');
Insert into SYSTEM.TBL_PRODUCT (ITEM_NO,ITEM_NAME,PRICE,S_RATE,P_RATE,CONTENTS,SELLYN,TRANS_INFO) values ('CLO1006','비즈니스 정장 세트',120000,0,0,'프로페셔널한 비즈니스 룩을 완성해주는 정장 세트','N','무료 배송');
Insert into SYSTEM.TBL_PRODUCT (ITEM_NO,ITEM_NAME,PRICE,S_RATE,P_RATE,CONTENTS,SELLYN,TRANS_INFO) values ('CLO1007','레트로 스타일 자켓',53900,0,0,'레트로 감성이 물씬 풍기는 스타일리시 자켓','N','착불 배송');
Insert into SYSTEM.TBL_PRODUCT (ITEM_NO,ITEM_NAME,PRICE,S_RATE,P_RATE,CONTENTS,SELLYN,TRANS_INFO) values ('CLO1008','플리츠 미니 스커트',26900,0,0,'다리라인을 예쁘게 보여주는 플리츠 미니 스커트','N','무료 배송');
Insert into SYSTEM.TBL_PRODUCT (ITEM_NO,ITEM_NAME,PRICE,S_RATE,P_RATE,CONTENTS,SELLYN,TRANS_INFO) values ('CLO1009','남성 기본 맨투맨',100000,0,0,'상남자만 입는 옷','N','무료 배송');
--------------------------------------------------------
--  DDL for Index PK_ITEM_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_ITEM_NO" ON "SYSTEM"."TBL_PRODUCT" ("ITEM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TBL_PRODUCT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBL_PRODUCT" MODIFY ("ITEM_NO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_PRODUCT" MODIFY ("ITEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_PRODUCT" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_PRODUCT" MODIFY ("S_RATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_PRODUCT" MODIFY ("P_RATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_PRODUCT" ADD CONSTRAINT "PK_ITEM_NO" PRIMARY KEY ("ITEM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
